version: '3.3'

services:
  frontendmovie:
    image: isbmovie:0.0.5
    build: "."
    ports:
      - "7075"
    restart: "always"
    networks:
      - "isbmovie.network"
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontendmovie
    ports:
      - "80:80"
    networks:
      - "isbmovie.network"
networks:
  isbmovie.network: